// source: google/firestore/v1/write.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_firestore_v1_common_pb = require('../../../google/firestore/v1/common_pb.js');
goog.object.extend(proto, google_firestore_v1_common_pb);
var google_firestore_v1_document_pb = require('../../../google/firestore/v1/document_pb.js');
goog.object.extend(proto, google_firestore_v1_document_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_api_annotations_pb = require('../../../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
goog.exportSymbol('proto.google.firestore.v1.DocumentChange', null, global);
goog.exportSymbol('proto.google.firestore.v1.DocumentDelete', null, global);
goog.exportSymbol('proto.google.firestore.v1.DocumentRemove', null, global);
goog.exportSymbol('proto.google.firestore.v1.DocumentTransform', null, global);
goog.exportSymbol('proto.google.firestore.v1.DocumentTransform.FieldTransform', null, global);
goog.exportSymbol('proto.google.firestore.v1.DocumentTransform.FieldTransform.ServerValue', null, global);
goog.exportSymbol('proto.google.firestore.v1.DocumentTransform.FieldTransform.TransformTypeCase', null, global);
goog.exportSymbol('proto.google.firestore.v1.ExistenceFilter', null, global);
goog.exportSymbol('proto.google.firestore.v1.Write', null, global);
goog.exportSymbol('proto.google.firestore.v1.Write.OperationCase', null, global);
goog.exportSymbol('proto.google.firestore.v1.WriteResult', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.firestore.v1.Write = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.firestore.v1.Write.repeatedFields_, proto.google.firestore.v1.Write.oneofGroups_);
};
goog.inherits(proto.google.firestore.v1.Write, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.firestore.v1.Write.displayName = 'proto.google.firestore.v1.Write';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.firestore.v1.DocumentTransform = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.firestore.v1.DocumentTransform.repeatedFields_, null);
};
goog.inherits(proto.google.firestore.v1.DocumentTransform, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.firestore.v1.DocumentTransform.displayName = 'proto.google.firestore.v1.DocumentTransform';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.google.firestore.v1.DocumentTransform.FieldTransform.oneofGroups_);
};
goog.inherits(proto.google.firestore.v1.DocumentTransform.FieldTransform, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.firestore.v1.DocumentTransform.FieldTransform.displayName = 'proto.google.firestore.v1.DocumentTransform.FieldTransform';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.firestore.v1.WriteResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.firestore.v1.WriteResult.repeatedFields_, null);
};
goog.inherits(proto.google.firestore.v1.WriteResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.firestore.v1.WriteResult.displayName = 'proto.google.firestore.v1.WriteResult';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.firestore.v1.DocumentChange = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.firestore.v1.DocumentChange.repeatedFields_, null);
};
goog.inherits(proto.google.firestore.v1.DocumentChange, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.firestore.v1.DocumentChange.displayName = 'proto.google.firestore.v1.DocumentChange';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.firestore.v1.DocumentDelete = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.firestore.v1.DocumentDelete.repeatedFields_, null);
};
goog.inherits(proto.google.firestore.v1.DocumentDelete, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.firestore.v1.DocumentDelete.displayName = 'proto.google.firestore.v1.DocumentDelete';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.firestore.v1.DocumentRemove = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.firestore.v1.DocumentRemove.repeatedFields_, null);
};
goog.inherits(proto.google.firestore.v1.DocumentRemove, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.firestore.v1.DocumentRemove.displayName = 'proto.google.firestore.v1.DocumentRemove';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.firestore.v1.ExistenceFilter = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.firestore.v1.ExistenceFilter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.firestore.v1.ExistenceFilter.displayName = 'proto.google.firestore.v1.ExistenceFilter';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.firestore.v1.Write.repeatedFields_ = [7];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.google.firestore.v1.Write.oneofGroups_ = [[1,2,6]];

/**
 * @enum {number}
 */
proto.google.firestore.v1.Write.OperationCase = {
  OPERATION_NOT_SET: 0,
  UPDATE: 1,
  DELETE: 2,
  TRANSFORM: 6
};

/**
 * @return {proto.google.firestore.v1.Write.OperationCase}
 */
proto.google.firestore.v1.Write.prototype.getOperationCase = function() {
  return /** @type {proto.google.firestore.v1.Write.OperationCase} */(jspb.Message.computeOneofCase(this, proto.google.firestore.v1.Write.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.firestore.v1.Write.prototype.toObject = function(opt_includeInstance) {
  return proto.google.firestore.v1.Write.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.firestore.v1.Write} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.firestore.v1.Write.toObject = function(includeInstance, msg) {
  var f, obj = {
    update: (f = msg.getUpdate()) && google_firestore_v1_document_pb.Document.toObject(includeInstance, f),
    pb_delete: jspb.Message.getFieldWithDefault(msg, 2, ""),
    transform: (f = msg.getTransform()) && proto.google.firestore.v1.DocumentTransform.toObject(includeInstance, f),
    updateMask: (f = msg.getUpdateMask()) && google_firestore_v1_common_pb.DocumentMask.toObject(includeInstance, f),
    updateTransformsList: jspb.Message.toObjectList(msg.getUpdateTransformsList(),
    proto.google.firestore.v1.DocumentTransform.FieldTransform.toObject, includeInstance),
    currentDocument: (f = msg.getCurrentDocument()) && google_firestore_v1_common_pb.Precondition.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.firestore.v1.Write}
 */
proto.google.firestore.v1.Write.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.firestore.v1.Write;
  return proto.google.firestore.v1.Write.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.firestore.v1.Write} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.firestore.v1.Write}
 */
proto.google.firestore.v1.Write.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_firestore_v1_document_pb.Document;
      reader.readMessage(value,google_firestore_v1_document_pb.Document.deserializeBinaryFromReader);
      msg.setUpdate(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDelete(value);
      break;
    case 6:
      var value = new proto.google.firestore.v1.DocumentTransform;
      reader.readMessage(value,proto.google.firestore.v1.DocumentTransform.deserializeBinaryFromReader);
      msg.setTransform(value);
      break;
    case 3:
      var value = new google_firestore_v1_common_pb.DocumentMask;
      reader.readMessage(value,google_firestore_v1_common_pb.DocumentMask.deserializeBinaryFromReader);
      msg.setUpdateMask(value);
      break;
    case 7:
      var value = new proto.google.firestore.v1.DocumentTransform.FieldTransform;
      reader.readMessage(value,proto.google.firestore.v1.DocumentTransform.FieldTransform.deserializeBinaryFromReader);
      msg.addUpdateTransforms(value);
      break;
    case 4:
      var value = new google_firestore_v1_common_pb.Precondition;
      reader.readMessage(value,google_firestore_v1_common_pb.Precondition.deserializeBinaryFromReader);
      msg.setCurrentDocument(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.firestore.v1.Write.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.firestore.v1.Write.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.firestore.v1.Write} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.firestore.v1.Write.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUpdate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_firestore_v1_document_pb.Document.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTransform();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.google.firestore.v1.DocumentTransform.serializeBinaryToWriter
    );
  }
  f = message.getUpdateMask();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_firestore_v1_common_pb.DocumentMask.serializeBinaryToWriter
    );
  }
  f = message.getUpdateTransformsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.google.firestore.v1.DocumentTransform.FieldTransform.serializeBinaryToWriter
    );
  }
  f = message.getCurrentDocument();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_firestore_v1_common_pb.Precondition.serializeBinaryToWriter
    );
  }
};


/**
 * optional Document update = 1;
 * @return {?proto.google.firestore.v1.Document}
 */
proto.google.firestore.v1.Write.prototype.getUpdate = function() {
  return /** @type{?proto.google.firestore.v1.Document} */ (
    jspb.Message.getWrapperField(this, google_firestore_v1_document_pb.Document, 1));
};


/**
 * @param {?proto.google.firestore.v1.Document|undefined} value
 * @return {!proto.google.firestore.v1.Write} returns this
*/
proto.google.firestore.v1.Write.prototype.setUpdate = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.google.firestore.v1.Write.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.firestore.v1.Write} returns this
 */
proto.google.firestore.v1.Write.prototype.clearUpdate = function() {
  return this.setUpdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.firestore.v1.Write.prototype.hasUpdate = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string delete = 2;
 * @return {string}
 */
proto.google.firestore.v1.Write.prototype.getDelete = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.firestore.v1.Write} returns this
 */
proto.google.firestore.v1.Write.prototype.setDelete = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.google.firestore.v1.Write.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.google.firestore.v1.Write} returns this
 */
proto.google.firestore.v1.Write.prototype.clearDelete = function() {
  return jspb.Message.setOneofField(this, 2, proto.google.firestore.v1.Write.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.firestore.v1.Write.prototype.hasDelete = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional DocumentTransform transform = 6;
 * @return {?proto.google.firestore.v1.DocumentTransform}
 */
proto.google.firestore.v1.Write.prototype.getTransform = function() {
  return /** @type{?proto.google.firestore.v1.DocumentTransform} */ (
    jspb.Message.getWrapperField(this, proto.google.firestore.v1.DocumentTransform, 6));
};


/**
 * @param {?proto.google.firestore.v1.DocumentTransform|undefined} value
 * @return {!proto.google.firestore.v1.Write} returns this
*/
proto.google.firestore.v1.Write.prototype.setTransform = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.google.firestore.v1.Write.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.firestore.v1.Write} returns this
 */
proto.google.firestore.v1.Write.prototype.clearTransform = function() {
  return this.setTransform(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.firestore.v1.Write.prototype.hasTransform = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional DocumentMask update_mask = 3;
 * @return {?proto.google.firestore.v1.DocumentMask}
 */
proto.google.firestore.v1.Write.prototype.getUpdateMask = function() {
  return /** @type{?proto.google.firestore.v1.DocumentMask} */ (
    jspb.Message.getWrapperField(this, google_firestore_v1_common_pb.DocumentMask, 3));
};


/**
 * @param {?proto.google.firestore.v1.DocumentMask|undefined} value
 * @return {!proto.google.firestore.v1.Write} returns this
*/
proto.google.firestore.v1.Write.prototype.setUpdateMask = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.firestore.v1.Write} returns this
 */
proto.google.firestore.v1.Write.prototype.clearUpdateMask = function() {
  return this.setUpdateMask(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.firestore.v1.Write.prototype.hasUpdateMask = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated DocumentTransform.FieldTransform update_transforms = 7;
 * @return {!Array<!proto.google.firestore.v1.DocumentTransform.FieldTransform>}
 */
proto.google.firestore.v1.Write.prototype.getUpdateTransformsList = function() {
  return /** @type{!Array<!proto.google.firestore.v1.DocumentTransform.FieldTransform>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.firestore.v1.DocumentTransform.FieldTransform, 7));
};


/**
 * @param {!Array<!proto.google.firestore.v1.DocumentTransform.FieldTransform>} value
 * @return {!proto.google.firestore.v1.Write} returns this
*/
proto.google.firestore.v1.Write.prototype.setUpdateTransformsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.google.firestore.v1.DocumentTransform.FieldTransform=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.firestore.v1.DocumentTransform.FieldTransform}
 */
proto.google.firestore.v1.Write.prototype.addUpdateTransforms = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.google.firestore.v1.DocumentTransform.FieldTransform, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.firestore.v1.Write} returns this
 */
proto.google.firestore.v1.Write.prototype.clearUpdateTransformsList = function() {
  return this.setUpdateTransformsList([]);
};


/**
 * optional Precondition current_document = 4;
 * @return {?proto.google.firestore.v1.Precondition}
 */
proto.google.firestore.v1.Write.prototype.getCurrentDocument = function() {
  return /** @type{?proto.google.firestore.v1.Precondition} */ (
    jspb.Message.getWrapperField(this, google_firestore_v1_common_pb.Precondition, 4));
};


/**
 * @param {?proto.google.firestore.v1.Precondition|undefined} value
 * @return {!proto.google.firestore.v1.Write} returns this
*/
proto.google.firestore.v1.Write.prototype.setCurrentDocument = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.firestore.v1.Write} returns this
 */
proto.google.firestore.v1.Write.prototype.clearCurrentDocument = function() {
  return this.setCurrentDocument(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.firestore.v1.Write.prototype.hasCurrentDocument = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.firestore.v1.DocumentTransform.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.firestore.v1.DocumentTransform.prototype.toObject = function(opt_includeInstance) {
  return proto.google.firestore.v1.DocumentTransform.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.firestore.v1.DocumentTransform} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.firestore.v1.DocumentTransform.toObject = function(includeInstance, msg) {
  var f, obj = {
    document: jspb.Message.getFieldWithDefault(msg, 1, ""),
    fieldTransformsList: jspb.Message.toObjectList(msg.getFieldTransformsList(),
    proto.google.firestore.v1.DocumentTransform.FieldTransform.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.firestore.v1.DocumentTransform}
 */
proto.google.firestore.v1.DocumentTransform.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.firestore.v1.DocumentTransform;
  return proto.google.firestore.v1.DocumentTransform.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.firestore.v1.DocumentTransform} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.firestore.v1.DocumentTransform}
 */
proto.google.firestore.v1.DocumentTransform.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDocument(value);
      break;
    case 2:
      var value = new proto.google.firestore.v1.DocumentTransform.FieldTransform;
      reader.readMessage(value,proto.google.firestore.v1.DocumentTransform.FieldTransform.deserializeBinaryFromReader);
      msg.addFieldTransforms(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.firestore.v1.DocumentTransform.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.firestore.v1.DocumentTransform.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.firestore.v1.DocumentTransform} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.firestore.v1.DocumentTransform.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDocument();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFieldTransformsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.google.firestore.v1.DocumentTransform.FieldTransform.serializeBinaryToWriter
    );
  }
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.oneofGroups_ = [[2,3,4,5,6,7]];

/**
 * @enum {number}
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.TransformTypeCase = {
  TRANSFORM_TYPE_NOT_SET: 0,
  SET_TO_SERVER_VALUE: 2,
  INCREMENT: 3,
  MAXIMUM: 4,
  MINIMUM: 5,
  APPEND_MISSING_ELEMENTS: 6,
  REMOVE_ALL_FROM_ARRAY: 7
};

/**
 * @return {proto.google.firestore.v1.DocumentTransform.FieldTransform.TransformTypeCase}
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.getTransformTypeCase = function() {
  return /** @type {proto.google.firestore.v1.DocumentTransform.FieldTransform.TransformTypeCase} */(jspb.Message.computeOneofCase(this, proto.google.firestore.v1.DocumentTransform.FieldTransform.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.toObject = function(opt_includeInstance) {
  return proto.google.firestore.v1.DocumentTransform.FieldTransform.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.firestore.v1.DocumentTransform.FieldTransform} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.toObject = function(includeInstance, msg) {
  var f, obj = {
    fieldPath: jspb.Message.getFieldWithDefault(msg, 1, ""),
    setToServerValue: jspb.Message.getFieldWithDefault(msg, 2, 0),
    increment: (f = msg.getIncrement()) && google_firestore_v1_document_pb.Value.toObject(includeInstance, f),
    maximum: (f = msg.getMaximum()) && google_firestore_v1_document_pb.Value.toObject(includeInstance, f),
    minimum: (f = msg.getMinimum()) && google_firestore_v1_document_pb.Value.toObject(includeInstance, f),
    appendMissingElements: (f = msg.getAppendMissingElements()) && google_firestore_v1_document_pb.ArrayValue.toObject(includeInstance, f),
    removeAllFromArray: (f = msg.getRemoveAllFromArray()) && google_firestore_v1_document_pb.ArrayValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.firestore.v1.DocumentTransform.FieldTransform}
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.firestore.v1.DocumentTransform.FieldTransform;
  return proto.google.firestore.v1.DocumentTransform.FieldTransform.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.firestore.v1.DocumentTransform.FieldTransform} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.firestore.v1.DocumentTransform.FieldTransform}
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFieldPath(value);
      break;
    case 2:
      var value = /** @type {!proto.google.firestore.v1.DocumentTransform.FieldTransform.ServerValue} */ (reader.readEnum());
      msg.setSetToServerValue(value);
      break;
    case 3:
      var value = new google_firestore_v1_document_pb.Value;
      reader.readMessage(value,google_firestore_v1_document_pb.Value.deserializeBinaryFromReader);
      msg.setIncrement(value);
      break;
    case 4:
      var value = new google_firestore_v1_document_pb.Value;
      reader.readMessage(value,google_firestore_v1_document_pb.Value.deserializeBinaryFromReader);
      msg.setMaximum(value);
      break;
    case 5:
      var value = new google_firestore_v1_document_pb.Value;
      reader.readMessage(value,google_firestore_v1_document_pb.Value.deserializeBinaryFromReader);
      msg.setMinimum(value);
      break;
    case 6:
      var value = new google_firestore_v1_document_pb.ArrayValue;
      reader.readMessage(value,google_firestore_v1_document_pb.ArrayValue.deserializeBinaryFromReader);
      msg.setAppendMissingElements(value);
      break;
    case 7:
      var value = new google_firestore_v1_document_pb.ArrayValue;
      reader.readMessage(value,google_firestore_v1_document_pb.ArrayValue.deserializeBinaryFromReader);
      msg.setRemoveAllFromArray(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.firestore.v1.DocumentTransform.FieldTransform.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.firestore.v1.DocumentTransform.FieldTransform} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFieldPath();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {!proto.google.firestore.v1.DocumentTransform.FieldTransform.ServerValue} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getIncrement();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_firestore_v1_document_pb.Value.serializeBinaryToWriter
    );
  }
  f = message.getMaximum();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_firestore_v1_document_pb.Value.serializeBinaryToWriter
    );
  }
  f = message.getMinimum();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_firestore_v1_document_pb.Value.serializeBinaryToWriter
    );
  }
  f = message.getAppendMissingElements();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_firestore_v1_document_pb.ArrayValue.serializeBinaryToWriter
    );
  }
  f = message.getRemoveAllFromArray();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_firestore_v1_document_pb.ArrayValue.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.ServerValue = {
  SERVER_VALUE_UNSPECIFIED: 0,
  REQUEST_TIME: 1
};

/**
 * optional string field_path = 1;
 * @return {string}
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.getFieldPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.firestore.v1.DocumentTransform.FieldTransform} returns this
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.setFieldPath = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional ServerValue set_to_server_value = 2;
 * @return {!proto.google.firestore.v1.DocumentTransform.FieldTransform.ServerValue}
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.getSetToServerValue = function() {
  return /** @type {!proto.google.firestore.v1.DocumentTransform.FieldTransform.ServerValue} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.google.firestore.v1.DocumentTransform.FieldTransform.ServerValue} value
 * @return {!proto.google.firestore.v1.DocumentTransform.FieldTransform} returns this
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.setSetToServerValue = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.google.firestore.v1.DocumentTransform.FieldTransform.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.google.firestore.v1.DocumentTransform.FieldTransform} returns this
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.clearSetToServerValue = function() {
  return jspb.Message.setOneofField(this, 2, proto.google.firestore.v1.DocumentTransform.FieldTransform.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.hasSetToServerValue = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Value increment = 3;
 * @return {?proto.google.firestore.v1.Value}
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.getIncrement = function() {
  return /** @type{?proto.google.firestore.v1.Value} */ (
    jspb.Message.getWrapperField(this, google_firestore_v1_document_pb.Value, 3));
};


/**
 * @param {?proto.google.firestore.v1.Value|undefined} value
 * @return {!proto.google.firestore.v1.DocumentTransform.FieldTransform} returns this
*/
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.setIncrement = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.google.firestore.v1.DocumentTransform.FieldTransform.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.firestore.v1.DocumentTransform.FieldTransform} returns this
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.clearIncrement = function() {
  return this.setIncrement(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.hasIncrement = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Value maximum = 4;
 * @return {?proto.google.firestore.v1.Value}
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.getMaximum = function() {
  return /** @type{?proto.google.firestore.v1.Value} */ (
    jspb.Message.getWrapperField(this, google_firestore_v1_document_pb.Value, 4));
};


/**
 * @param {?proto.google.firestore.v1.Value|undefined} value
 * @return {!proto.google.firestore.v1.DocumentTransform.FieldTransform} returns this
*/
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.setMaximum = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.google.firestore.v1.DocumentTransform.FieldTransform.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.firestore.v1.DocumentTransform.FieldTransform} returns this
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.clearMaximum = function() {
  return this.setMaximum(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.hasMaximum = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional Value minimum = 5;
 * @return {?proto.google.firestore.v1.Value}
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.getMinimum = function() {
  return /** @type{?proto.google.firestore.v1.Value} */ (
    jspb.Message.getWrapperField(this, google_firestore_v1_document_pb.Value, 5));
};


/**
 * @param {?proto.google.firestore.v1.Value|undefined} value
 * @return {!proto.google.firestore.v1.DocumentTransform.FieldTransform} returns this
*/
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.setMinimum = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.google.firestore.v1.DocumentTransform.FieldTransform.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.firestore.v1.DocumentTransform.FieldTransform} returns this
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.clearMinimum = function() {
  return this.setMinimum(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.hasMinimum = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional ArrayValue append_missing_elements = 6;
 * @return {?proto.google.firestore.v1.ArrayValue}
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.getAppendMissingElements = function() {
  return /** @type{?proto.google.firestore.v1.ArrayValue} */ (
    jspb.Message.getWrapperField(this, google_firestore_v1_document_pb.ArrayValue, 6));
};


/**
 * @param {?proto.google.firestore.v1.ArrayValue|undefined} value
 * @return {!proto.google.firestore.v1.DocumentTransform.FieldTransform} returns this
*/
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.setAppendMissingElements = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.google.firestore.v1.DocumentTransform.FieldTransform.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.firestore.v1.DocumentTransform.FieldTransform} returns this
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.clearAppendMissingElements = function() {
  return this.setAppendMissingElements(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.hasAppendMissingElements = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional ArrayValue remove_all_from_array = 7;
 * @return {?proto.google.firestore.v1.ArrayValue}
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.getRemoveAllFromArray = function() {
  return /** @type{?proto.google.firestore.v1.ArrayValue} */ (
    jspb.Message.getWrapperField(this, google_firestore_v1_document_pb.ArrayValue, 7));
};


/**
 * @param {?proto.google.firestore.v1.ArrayValue|undefined} value
 * @return {!proto.google.firestore.v1.DocumentTransform.FieldTransform} returns this
*/
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.setRemoveAllFromArray = function(value) {
  return jspb.Message.setOneofWrapperField(this, 7, proto.google.firestore.v1.DocumentTransform.FieldTransform.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.firestore.v1.DocumentTransform.FieldTransform} returns this
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.clearRemoveAllFromArray = function() {
  return this.setRemoveAllFromArray(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.firestore.v1.DocumentTransform.FieldTransform.prototype.hasRemoveAllFromArray = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string document = 1;
 * @return {string}
 */
proto.google.firestore.v1.DocumentTransform.prototype.getDocument = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.firestore.v1.DocumentTransform} returns this
 */
proto.google.firestore.v1.DocumentTransform.prototype.setDocument = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated FieldTransform field_transforms = 2;
 * @return {!Array<!proto.google.firestore.v1.DocumentTransform.FieldTransform>}
 */
proto.google.firestore.v1.DocumentTransform.prototype.getFieldTransformsList = function() {
  return /** @type{!Array<!proto.google.firestore.v1.DocumentTransform.FieldTransform>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.firestore.v1.DocumentTransform.FieldTransform, 2));
};


/**
 * @param {!Array<!proto.google.firestore.v1.DocumentTransform.FieldTransform>} value
 * @return {!proto.google.firestore.v1.DocumentTransform} returns this
*/
proto.google.firestore.v1.DocumentTransform.prototype.setFieldTransformsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.google.firestore.v1.DocumentTransform.FieldTransform=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.firestore.v1.DocumentTransform.FieldTransform}
 */
proto.google.firestore.v1.DocumentTransform.prototype.addFieldTransforms = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.google.firestore.v1.DocumentTransform.FieldTransform, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.firestore.v1.DocumentTransform} returns this
 */
proto.google.firestore.v1.DocumentTransform.prototype.clearFieldTransformsList = function() {
  return this.setFieldTransformsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.firestore.v1.WriteResult.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.firestore.v1.WriteResult.prototype.toObject = function(opt_includeInstance) {
  return proto.google.firestore.v1.WriteResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.firestore.v1.WriteResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.firestore.v1.WriteResult.toObject = function(includeInstance, msg) {
  var f, obj = {
    updateTime: (f = msg.getUpdateTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    transformResultsList: jspb.Message.toObjectList(msg.getTransformResultsList(),
    google_firestore_v1_document_pb.Value.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.firestore.v1.WriteResult}
 */
proto.google.firestore.v1.WriteResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.firestore.v1.WriteResult;
  return proto.google.firestore.v1.WriteResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.firestore.v1.WriteResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.firestore.v1.WriteResult}
 */
proto.google.firestore.v1.WriteResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdateTime(value);
      break;
    case 2:
      var value = new google_firestore_v1_document_pb.Value;
      reader.readMessage(value,google_firestore_v1_document_pb.Value.deserializeBinaryFromReader);
      msg.addTransformResults(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.firestore.v1.WriteResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.firestore.v1.WriteResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.firestore.v1.WriteResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.firestore.v1.WriteResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUpdateTime();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getTransformResultsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      google_firestore_v1_document_pb.Value.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Timestamp update_time = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.firestore.v1.WriteResult.prototype.getUpdateTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.firestore.v1.WriteResult} returns this
*/
proto.google.firestore.v1.WriteResult.prototype.setUpdateTime = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.firestore.v1.WriteResult} returns this
 */
proto.google.firestore.v1.WriteResult.prototype.clearUpdateTime = function() {
  return this.setUpdateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.firestore.v1.WriteResult.prototype.hasUpdateTime = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Value transform_results = 2;
 * @return {!Array<!proto.google.firestore.v1.Value>}
 */
proto.google.firestore.v1.WriteResult.prototype.getTransformResultsList = function() {
  return /** @type{!Array<!proto.google.firestore.v1.Value>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_firestore_v1_document_pb.Value, 2));
};


/**
 * @param {!Array<!proto.google.firestore.v1.Value>} value
 * @return {!proto.google.firestore.v1.WriteResult} returns this
*/
proto.google.firestore.v1.WriteResult.prototype.setTransformResultsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.google.firestore.v1.Value=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.firestore.v1.Value}
 */
proto.google.firestore.v1.WriteResult.prototype.addTransformResults = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.google.firestore.v1.Value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.firestore.v1.WriteResult} returns this
 */
proto.google.firestore.v1.WriteResult.prototype.clearTransformResultsList = function() {
  return this.setTransformResultsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.firestore.v1.DocumentChange.repeatedFields_ = [5,6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.firestore.v1.DocumentChange.prototype.toObject = function(opt_includeInstance) {
  return proto.google.firestore.v1.DocumentChange.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.firestore.v1.DocumentChange} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.firestore.v1.DocumentChange.toObject = function(includeInstance, msg) {
  var f, obj = {
    document: (f = msg.getDocument()) && google_firestore_v1_document_pb.Document.toObject(includeInstance, f),
    targetIdsList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    removedTargetIdsList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.firestore.v1.DocumentChange}
 */
proto.google.firestore.v1.DocumentChange.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.firestore.v1.DocumentChange;
  return proto.google.firestore.v1.DocumentChange.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.firestore.v1.DocumentChange} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.firestore.v1.DocumentChange}
 */
proto.google.firestore.v1.DocumentChange.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_firestore_v1_document_pb.Document;
      reader.readMessage(value,google_firestore_v1_document_pb.Document.deserializeBinaryFromReader);
      msg.setDocument(value);
      break;
    case 5:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addTargetIds(values[i]);
      }
      break;
    case 6:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addRemovedTargetIds(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.firestore.v1.DocumentChange.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.firestore.v1.DocumentChange.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.firestore.v1.DocumentChange} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.firestore.v1.DocumentChange.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDocument();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_firestore_v1_document_pb.Document.serializeBinaryToWriter
    );
  }
  f = message.getTargetIdsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      5,
      f
    );
  }
  f = message.getRemovedTargetIdsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      6,
      f
    );
  }
};


/**
 * optional Document document = 1;
 * @return {?proto.google.firestore.v1.Document}
 */
proto.google.firestore.v1.DocumentChange.prototype.getDocument = function() {
  return /** @type{?proto.google.firestore.v1.Document} */ (
    jspb.Message.getWrapperField(this, google_firestore_v1_document_pb.Document, 1));
};


/**
 * @param {?proto.google.firestore.v1.Document|undefined} value
 * @return {!proto.google.firestore.v1.DocumentChange} returns this
*/
proto.google.firestore.v1.DocumentChange.prototype.setDocument = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.firestore.v1.DocumentChange} returns this
 */
proto.google.firestore.v1.DocumentChange.prototype.clearDocument = function() {
  return this.setDocument(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.firestore.v1.DocumentChange.prototype.hasDocument = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated int32 target_ids = 5;
 * @return {!Array<number>}
 */
proto.google.firestore.v1.DocumentChange.prototype.getTargetIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.google.firestore.v1.DocumentChange} returns this
 */
proto.google.firestore.v1.DocumentChange.prototype.setTargetIdsList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.google.firestore.v1.DocumentChange} returns this
 */
proto.google.firestore.v1.DocumentChange.prototype.addTargetIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.firestore.v1.DocumentChange} returns this
 */
proto.google.firestore.v1.DocumentChange.prototype.clearTargetIdsList = function() {
  return this.setTargetIdsList([]);
};


/**
 * repeated int32 removed_target_ids = 6;
 * @return {!Array<number>}
 */
proto.google.firestore.v1.DocumentChange.prototype.getRemovedTargetIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.google.firestore.v1.DocumentChange} returns this
 */
proto.google.firestore.v1.DocumentChange.prototype.setRemovedTargetIdsList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.google.firestore.v1.DocumentChange} returns this
 */
proto.google.firestore.v1.DocumentChange.prototype.addRemovedTargetIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.firestore.v1.DocumentChange} returns this
 */
proto.google.firestore.v1.DocumentChange.prototype.clearRemovedTargetIdsList = function() {
  return this.setRemovedTargetIdsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.firestore.v1.DocumentDelete.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.firestore.v1.DocumentDelete.prototype.toObject = function(opt_includeInstance) {
  return proto.google.firestore.v1.DocumentDelete.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.firestore.v1.DocumentDelete} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.firestore.v1.DocumentDelete.toObject = function(includeInstance, msg) {
  var f, obj = {
    document: jspb.Message.getFieldWithDefault(msg, 1, ""),
    removedTargetIdsList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f,
    readTime: (f = msg.getReadTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.firestore.v1.DocumentDelete}
 */
proto.google.firestore.v1.DocumentDelete.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.firestore.v1.DocumentDelete;
  return proto.google.firestore.v1.DocumentDelete.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.firestore.v1.DocumentDelete} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.firestore.v1.DocumentDelete}
 */
proto.google.firestore.v1.DocumentDelete.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDocument(value);
      break;
    case 6:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addRemovedTargetIds(values[i]);
      }
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setReadTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.firestore.v1.DocumentDelete.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.firestore.v1.DocumentDelete.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.firestore.v1.DocumentDelete} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.firestore.v1.DocumentDelete.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDocument();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRemovedTargetIdsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      6,
      f
    );
  }
  f = message.getReadTime();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string document = 1;
 * @return {string}
 */
proto.google.firestore.v1.DocumentDelete.prototype.getDocument = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.firestore.v1.DocumentDelete} returns this
 */
proto.google.firestore.v1.DocumentDelete.prototype.setDocument = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated int32 removed_target_ids = 6;
 * @return {!Array<number>}
 */
proto.google.firestore.v1.DocumentDelete.prototype.getRemovedTargetIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.google.firestore.v1.DocumentDelete} returns this
 */
proto.google.firestore.v1.DocumentDelete.prototype.setRemovedTargetIdsList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.google.firestore.v1.DocumentDelete} returns this
 */
proto.google.firestore.v1.DocumentDelete.prototype.addRemovedTargetIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.firestore.v1.DocumentDelete} returns this
 */
proto.google.firestore.v1.DocumentDelete.prototype.clearRemovedTargetIdsList = function() {
  return this.setRemovedTargetIdsList([]);
};


/**
 * optional google.protobuf.Timestamp read_time = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.firestore.v1.DocumentDelete.prototype.getReadTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.firestore.v1.DocumentDelete} returns this
*/
proto.google.firestore.v1.DocumentDelete.prototype.setReadTime = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.firestore.v1.DocumentDelete} returns this
 */
proto.google.firestore.v1.DocumentDelete.prototype.clearReadTime = function() {
  return this.setReadTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.firestore.v1.DocumentDelete.prototype.hasReadTime = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.firestore.v1.DocumentRemove.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.firestore.v1.DocumentRemove.prototype.toObject = function(opt_includeInstance) {
  return proto.google.firestore.v1.DocumentRemove.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.firestore.v1.DocumentRemove} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.firestore.v1.DocumentRemove.toObject = function(includeInstance, msg) {
  var f, obj = {
    document: jspb.Message.getFieldWithDefault(msg, 1, ""),
    removedTargetIdsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    readTime: (f = msg.getReadTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.firestore.v1.DocumentRemove}
 */
proto.google.firestore.v1.DocumentRemove.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.firestore.v1.DocumentRemove;
  return proto.google.firestore.v1.DocumentRemove.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.firestore.v1.DocumentRemove} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.firestore.v1.DocumentRemove}
 */
proto.google.firestore.v1.DocumentRemove.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDocument(value);
      break;
    case 2:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addRemovedTargetIds(values[i]);
      }
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setReadTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.firestore.v1.DocumentRemove.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.firestore.v1.DocumentRemove.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.firestore.v1.DocumentRemove} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.firestore.v1.DocumentRemove.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDocument();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRemovedTargetIdsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      2,
      f
    );
  }
  f = message.getReadTime();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string document = 1;
 * @return {string}
 */
proto.google.firestore.v1.DocumentRemove.prototype.getDocument = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.firestore.v1.DocumentRemove} returns this
 */
proto.google.firestore.v1.DocumentRemove.prototype.setDocument = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated int32 removed_target_ids = 2;
 * @return {!Array<number>}
 */
proto.google.firestore.v1.DocumentRemove.prototype.getRemovedTargetIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.google.firestore.v1.DocumentRemove} returns this
 */
proto.google.firestore.v1.DocumentRemove.prototype.setRemovedTargetIdsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.google.firestore.v1.DocumentRemove} returns this
 */
proto.google.firestore.v1.DocumentRemove.prototype.addRemovedTargetIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.firestore.v1.DocumentRemove} returns this
 */
proto.google.firestore.v1.DocumentRemove.prototype.clearRemovedTargetIdsList = function() {
  return this.setRemovedTargetIdsList([]);
};


/**
 * optional google.protobuf.Timestamp read_time = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.firestore.v1.DocumentRemove.prototype.getReadTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.firestore.v1.DocumentRemove} returns this
*/
proto.google.firestore.v1.DocumentRemove.prototype.setReadTime = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.firestore.v1.DocumentRemove} returns this
 */
proto.google.firestore.v1.DocumentRemove.prototype.clearReadTime = function() {
  return this.setReadTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.firestore.v1.DocumentRemove.prototype.hasReadTime = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.firestore.v1.ExistenceFilter.prototype.toObject = function(opt_includeInstance) {
  return proto.google.firestore.v1.ExistenceFilter.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.firestore.v1.ExistenceFilter} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.firestore.v1.ExistenceFilter.toObject = function(includeInstance, msg) {
  var f, obj = {
    targetId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    count: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.firestore.v1.ExistenceFilter}
 */
proto.google.firestore.v1.ExistenceFilter.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.firestore.v1.ExistenceFilter;
  return proto.google.firestore.v1.ExistenceFilter.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.firestore.v1.ExistenceFilter} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.firestore.v1.ExistenceFilter}
 */
proto.google.firestore.v1.ExistenceFilter.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTargetId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.firestore.v1.ExistenceFilter.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.firestore.v1.ExistenceFilter.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.firestore.v1.ExistenceFilter} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.firestore.v1.ExistenceFilter.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTargetId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getCount();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional int32 target_id = 1;
 * @return {number}
 */
proto.google.firestore.v1.ExistenceFilter.prototype.getTargetId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.firestore.v1.ExistenceFilter} returns this
 */
proto.google.firestore.v1.ExistenceFilter.prototype.setTargetId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 count = 2;
 * @return {number}
 */
proto.google.firestore.v1.ExistenceFilter.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.firestore.v1.ExistenceFilter} returns this
 */
proto.google.firestore.v1.ExistenceFilter.prototype.setCount = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


goog.object.extend(exports, proto.google.firestore.v1);
