version: '2'
services:

  db:
    container_name: db
    image: postgres:${PG_VERSION}
    ports:
      - "${DB_PORT}:5432"
    environment:
      # the values are defined in the .env file
      # env vars specific to postgres image used on first boot
      - POSTGRES_USER=${SUPER_USER}
      - POSTGRES_PASSWORD=${SUPER_USER_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      # env vars useful for our sql scripts
      - SUPER_USER=${SUPER_USER}
      - SUPER_USER_PASSWORD=${SUPER_USER_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_ANON_ROLE=${DB_ANON_ROLE}
      - DEVELOPMENT=${DEVELOPMENT}
      - JWT_SECRET=${JWT_SECRET}

    volumes:
      - "./db/src:/docker-entrypoint-initdb.d"
  ### DB END

  subzero:
    container_name: subzero
    image: subzerocloud/subzero-development-grpc:latest
    # build: 
    #   context: ./grpc
    ports:
      - "8080:80"
      - "8443:443"
      # - "9443:9443"
      # - "9080:9080"
      - "6789:6789"
    environment:
      # the values are defined in the .env file
      # postgrest specific settings
      - PGRST_DB_URI=postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?application_name=subzero
      - PGRST_JWT_SECRET=${JWT_SECRET}
      - PGRST_DB_SCHEMA=${DB_SCHEMA}
      - PGRST_DB_ANON_ROLE=${DB_ANON_ROLE}
      - PGRST_SERVER_PROXY_URI=${SERVER_PROXY_URI}
      # uncomment to also see postgrest output in the logs
      - PGRST_LOGFILE=/dev/fd/1
      - PGRST_LOG_LEVEL=info

      # openresty
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - DB_ANON_ROLE=${DB_ANON_ROLE}
      - DEVELOPMENT=${DEVELOPMENT}
      - ENABLE_CACHE=${ENABLE_CACHE}
      - ERR_LOGLEVEL=info

      # oauth providers
      - OAUTH_SUCCESS_URI=/rest/rpc/on_oauth_login
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
      - OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}
      - OAUTH_GITHUB_CLIENT_ID=${OAUTH_GITHUB_CLIENT_ID}
      - OAUTH_GITHUB_CLIENT_SECRET=${OAUTH_GITHUB_CLIENT_SECRET}
      - OAUTH_FACEBOOK_CLIENT_ID=${OAUTH_FACEBOOK_CLIENT_ID}
      - OAUTH_FACEBOOK_CLIENT_SECRET=${OAUTH_FACEBOOK_CLIENT_SECRET}

      # auto-ssl list the domains separated by comma for which an ssl certificate shoudl be fetched
      # - SSL_ALLOWED_DOMAINS="mydomain.com"

      # grpc
      - GRPC_PORT=6789
      - GRPC_REST_ENDPOINT=http://localhost:80/rest
      - GRPC_PROJECT_ID=dummy-project-id
      - GRPC_DATABASE_NAME=(default)
      - GRPC_LIVE_UPDATE_INTERVAL=1000
      - GRPC_JWT_SECRET=${JWT_SECRET}
      - GRPC_VERBOSITY=DEBUG
      - GRPC_TRACE=all 
    volumes:
      - "./html:/usr/local/openresty/nginx/html"
      - "./grpc/dist/grpc_server.js:/usr/local/bin/grpc_server.js"
      - "./supervisord/grpc.conf:/etc/supervisor.d/grpc.conf"
      
      # - ./openresty/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      # - ./openresty/nginx/grpc.conf:/usr/local/openresty/nginx/conf/grpc.conf
      # - "./supervisord/grpcwebproxy.conf:/etc/supervisor.d/grpcwebproxy.conf"

